### PR TITLE
Add Dom.Storage.setItem and Dom.Storage2.setItem

### LINKED ISSUE #93: Dom.Storage and Dom.Storage2 module missing setItem
Looks like the docs are missing the `setItem` functions from the Dom.Storage modules.

### PR DESCRIPTION
**Pull request by dan003400**
Fixes #93

### CODE REVIEW

**Comment by ryyppy** [comment]
duplicate of #85, but happy to merge this is you add the same changes to the `v8.0.0` docs with proper Reason syntax.

**Comment by dan003400** [comment]
> duplicate of #85, but happy to merge this is you add the same changes to the `v8.0.0` docs with proper Reason syntax.

Done.

**Comment by ryyppy** [comment]
Sorry Dan, #85 by @bodhish was replying faster than expected, so I went ahead and merged his' first 😅

**Comment by ryyppy** [comment]
Okay will close this since the feature is already in master!

**Pull request closed without merging**
