### PR TITLE
promise.mdx: replace deprecated pipe

### PR DESCRIPTION
**Pull request by theqp**
with the new version

### CODE REVIEW

**Comment by theqp** [comment]
@ryyppy Thanks for the feedback. I couldn't find any formatter for ReScript, and your example is more different from the original version than mine.

**Comment by ryyppy** [comment]
The [ReScript Playground](https://rescript-lang.org/try) has a "Format" button to pretty print your code.

The code looks different because the |> operator is actually an infix, and the -> operator is syntax. The latter doesn't introduce white space between the left- and righthand side values, so `values -> myFn` kinda looks off

**Comment by theqp** [comment]
@ryyppy I have pretty printed the code snipet as suggested

**Comment by ryyppy** [comment]
Thanks!

**Pull request merged**
